### ISSUE TITLE
Set up TravisCI

### ISSUE THREAD

**Issue by richleland** [SparkPost/gosparkpost#23]
- I can help do this after the repo is public

**Comment by VojtechVitek** [comment]
@richleland @yepher @yargevad do you guys think you could enable Travis for this repository?

Since you can run
```
SPARKPOST_BASEURL="https://api.sparkpost.com" SPARKPOST_API_KEY="KEY" go test
```
..it should be as simple as setting two ENV VARS in the Travis config for this repo. See https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings

Maybe you could even point the BASEURL to the SparkPost Mock server?

//cc @pxue

**Comment by yargevad** [comment]
@VojtechVitek Travis is already enabled - are you asking about re-enabling the tests?

We're actually going to refactor the tests a bit in the near future. Let's chat on slack if you'd like to have a more detailed discussion.

**Comment by yargevad** [comment]
Travis is enabled, working on tests in separate issues.
