### ISSUE TITLE
Removing `ErrWebhookValidation`?

### ISSUE THREAD

**Issue by mostafah** [SparkPost/gosparkpost#52]
Validation is not an error. It’s just an empty request and should return an empty list of events with no error. An empty list means the user won’t do anything, after all.

Returning an error when there is not one forces the user to check for this particular error and ignore it, which is not nice code. Removing this error makes it easier to use the `events` package.

So, what is the use of this special error? Is there a reason for keeping it? (Don’t know about compatibility policy of this package.)

I can send a PR for its removal if you agree with this.

**Comment by yargevad** [comment]
Hi @mostafah, removing that error and returning an empty list instead sounds good to me.

**Comment by mostafah** [comment]
PR: #65

**Comment by yargevad** [comment]
Thanks!

**Comment by VojtechVitek** [comment]
#65 is not a full fix, since it removes the "webhook validation" feature.

I agree that `ErrWebhookValidation` is not really an error -- but it's a special Sparkpost API response for webhook endpoint validation -- the API returns `Empty "msys" wrapper` only on this "ping", nowhere else (yeah, not really a handy API response).

So, how do you guys recognize that Sparkpost pinged your API with this special value now?

@yargevad Dave, can you re-open this issue, so we can track down real fix?

**Comment by mostafah** [comment]
@VojtechVitek I worked on this months ago and may not remember the details well. But from what I can remember, shouldn’t an empty list of events mean the same thing? I mean, if there are zero events reported, that means it’s not a real post and a validation one. But this is probably not documented.

**Comment by VojtechVitek** [comment]
@mostafah yeah, that'd make sense. It's not documented, though.
