### ISSUE TITLE
subaccount api: support all documented methods

### ISSUE THREAD

**Issue by pxue** [SparkPost/gosparkpost#55]
https://developers.sparkpost.com/api/#/reference/subaccounts

**Comment by pxue** [comment]
hey @kakysha thanks for the subaccount + client header update.

questions/concerns about the client header though:
1) since header is configured on the client, we need to create/destroy or build a lookup table of thousands of subclient / clients.
2) if we build a global client, the struct needs to have a mutex to be concurrency safe

any suggestion on what's the better approach?

**Comment by kakysha** [comment]
@pxue as for me, better approach is to set subaccount_id on every API call, but these required me to refactor code, which I was against, I decided to make it in Client.
To make it thread-safe I beleive its better to guard writes to headers by mutex, cant see the situation in which mutex overhead could be a big problem.

**Comment by yargevad** [comment]
Something we've been discussing internally is, instead of having the `map[string]string` as a part of the `Client`, adding `Headers *map[string]string` on the various objects like `Transmissions`.

The idea would be that you could build a `map[string]string` with your subaccount-specific details (even api key in `Authorization` if that's part of your use case), and reference that `map` to include those headers on requests using that object.

Thoughts on that? @pxue I think that'll avoid the create/destroy and mutex issues you mentioned above.

**Comment by pxue** [comment]
@yargevad that would be ideal. makes sense since Mandrill allows subaccount settings on send message call as well.

**Comment by kakysha** [comment]
@pxue yeah, that is what I meant by saying 'set subaccount on every API call' :)

**Comment by yargevad** [comment]
Hi @pxue, I'm hearing that you would like to use our subaccount feature, but haven't because this issue isn't resolved. Is that correct?

**Comment by yargevad** [comment]
Setting subaccount (and API key) on a per-request basis is now supported with #80 - let me know how it goes once you've had a look and/or tried it out!
